### ISSUE TITLE
No provider for "framework:cucumber-js"! (Resolving: framework:cucumber-js)

### ISSUE THREAD

**Issue by JimLynchCodes** [eugene-sea/karma-cucumber-js#8]
Odd, I followed all of the steps, but when I run the command: `` I still get this error: 

/Users/jim/Git-Projects/Flexbox-Push-Drawer-Example/node_modules/di/lib/injector.js:9
      throw error('No provider for "' + name + '"!');
      ^

Error: No provider for "framework:cucumber-js"! (Resolving: framework:cucumber-js)
    at error (/Users/jim/Git-Projects/Flexbox-Push-Drawer-Example/node_modules/di/lib/injector.js:22:12)
    at Object.parent.get (/Users/jim/Git-Projects/Flexbox-Push-Drawer-Example/node_modules/di/lib/injector.js:9:13)
    at get (/Users/jim/Git-Projects/Flexbox-Push-Drawer-Example/node_modules/di/lib/injector.js:54:19)
    at /Users/jim/Git-Projects/Flexbox-Push-Drawer-Example/node_modules/karma/lib/server.js:138:20
    at Array.forEach (native)
    at Server._start (/Users/jim/Git-Projects/Flexbox-Push-Drawer-Example/node_modules/karma/lib/server.js:137:21)
    at invoke (/Users/jim/Git-Projects/Flexbox-Push-Drawer-Example/node_modules/di/lib/injector.js:75:15)
    at Server.start (/Users/jim/Git-Projects/Flexbox-Push-Drawer-Example/node_modules/karma/lib/server.js:102:18)
    at Object.exports.run (/Users/jim/Git-Projects/Flexbox-Push-Drawer-Example/node_modules/karma/lib/cli.js:243:26)
    at Object.<anonymous> (/Users/jim/Git-Projects/Flexbox-Push-Drawer-Example/node_modules/karma/bin/karma:3:23)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)

![flexbox-push-drawer-example_ _-bash_ _157x24_and_eugene-sea_karma-cucumber-js__karma_adapter_for_running_cucumber_js_features_and_karma-c_conf_js_-_flexbox-push-drawer-example_-____git-projects_flexbox-push-drawer-example_](https://cloud.githubusercontent.com/assets/5354163/17647617/03b5e074-61c6-11e6-8f77-e5eaf11485dd.png)

**Comment by eugene-sea** [comment]
Is this project present on GitHub? I need to look at it to help.

**Comment by eugene-sea** [comment]
If it is not present post here your karma.conf.js and output from karma with verbose logging ("--log-level=DEBUG")

**Comment by JimLynchCodes** [comment]
Hi. Thanks for the quick response! Unfortunately, I used your config file exactly (changing the js to ts though), but it still doesn't work; exact same error. Also, what is "./lib/index.js'"?

The project is on github here:https://github.com/JimTheMan/Flexbox-Push-Drawer-Example

Thanks.

![flexbox-push-drawer-example_ _-bash_ _157x27](https://cloud.githubusercontent.com/assets/5354163/17649916/e8eaf9e4-620d-11e6-836e-262e8c8fa864.png)

**Comment by eugene-sea** [comment]
You do not need `"./lib/index.js"`.

The issue is with somewhat confusing karma behavior. If you specify at least one plugin in `karma.conf.js` then you need to specify all frameworks also in `plugins` section like this:

```
    frameworks: ['cucumber-js'],

    plugins: [
      'karma-chrome-launcher',
      'karma-cucumber-js'
    ],
```

If you do not have `plugins` section, then just `frameworks` section will be enough. In your case you could omit `karma-chrome-launcher` and so if you do not need any other plugins then just remove whole `plugins` section and it will work (just leave `frameworks` section).

**Comment by eugene-sea** [comment]
I have updated [README.md](https://github.com/eugene-sea/karma-cucumber-js/blob/master/README.md) to cover this case

**Comment by JimLynchCodes** [comment]
HUZZAAH!

I've been bouncing back and forth between this and the s9tpepper project trying to get one working. My problem was that in the plugins section I had 'karma-cucumberjs' instead of  'karma-cucumber-js'.

Phew, now that I have something working I can get down to the real work. :) 

Anyway, thanks for writing this library and helping me out!
